name: basesspcloud
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - aiobotocore=2.1.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py310h6acc77f_0
  - aiohttp-retry=2.4.6=pyhd8ed1ab_1
  - aioitertools=0.10.0=pyhd8ed1ab_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - astroid=2.9.3=py310hff52083_0
  - asttokens=2.0.5=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - asyncssh=2.8.1=pyhd8ed1ab_0
  - atk-1.0=2.36.0=h3371d22_4
  - atpublic=3.0.1=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - boto3=1.20.24=pyhd8ed1ab_0
  - botocore=1.23.24=pyhd8ed1ab_0
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brotlipy=0.7.0=py310h6acc77f_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.2.1=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.15.0=py310hd667e15_1
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - commonmark=0.9.1=py_0
  - configobj=5.0.6=py_0
  - cryptography=36.0.1=py310h685ca39_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.5.1=py310h122e73d_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - dictdiffer=0.9.0=pyhd8ed1ab_0
  - diskcache=5.4.0=pyhd8ed1ab_0
  - distro=1.6.0=pyhd8ed1ab_0
  - dpath=2.0.6=py310hff52083_0
  - dulwich=0.20.33=py310h5764c6d_0
  - dvc=2.9.5=py310hff52083_0
  - dvc-s3=2.9.5=py310hff52083_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.3=pyhd8ed1ab_0
  - expat=2.4.7=h27087fc_0
  - flake8=4.0.1=pyhd8ed1ab_2
  - flatten-dict=0.4.2=pyhd8ed1ab_1
  - flufl.lock=7.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.13.1=h6c09931_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.29.1=py310h6acc77f_0
  - freetype=2.10.4=h0708190_1
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.3.0=py310h6acc77f_0
  - fsspec=2022.2.0=pyhd8ed1ab_0
  - ftfy=5.5.1=py_0
  - funcy=1.17=pyhd8ed1ab_0
  - future=0.18.2=py310hff52083_4
  - gdk-pixbuf=2.42.6=h04a7f16_0
  - gettext=0.19.8.1=h0b5b191_1005
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - grandalf=0.6=py_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=2.49.0=h85b4f2f_0
  - gtk2=2.24.33=h539f30e_1
  - gts=0.7.6=h64030ff_2
  - harfbuzz=3.0.0=h83ec7ef_1
  - icu=68.2=h9c3ff4c_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.2=py310hff52083_0
  - iniconfig=1.1.1=pyh9f0ad1d_0
  - ipykernel=6.9.1=py310hfdc917e_0
  - ipython=8.1.1=py310hff52083_0
  - isort=5.10.1=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py310hff52083_0
  - jmespath=0.10.0=pyh9f0ad1d_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h7f98852_0
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_core=4.9.2=py310hff52083_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.3.2=py310h91b1402_1
  - krb5=1.19.2=h3790be6_4
  - lazy-object-proxy=1.7.1=py310h6acc77f_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=13_linux64_openblas
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=13_linux64_openblas
  - libdeflate=1.7=h7f98852_5
  - libedit=3.1.20191231=he28a2e2_2
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1d223b6_13
  - libgd=2.3.3=h6ad9fb6_0
  - libgfortran-ng=11.2.0=h69a702a_13
  - libgfortran5=11.2.0=h5c6108e_13
  - libgit2=1.3.0=hee63804_1
  - libglib=2.68.4=h3e27bee_0
  - libgomp=11.2.0=h1d223b6_13
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=13_linux64_openblas
  - libopenblas=0.3.18=pthreads_h8fe5266_0
  - libpng=1.6.37=h21135ba_2
  - librsvg=2.52.2=hc3c00ef_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_13
  - libtiff=4.3.0=hf544144_1
  - libtool=2.4.6=h9c3ff4c_1008
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - libxcb=1.13=h7f98852_1004
  - libxgboost=1.5.1=cpu_h3d145d1_2
  - libxml2=2.9.12=h72842e0_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - mailchecker=4.1.13=pyhd8ed1ab_0
  - matplotlib-base=3.5.1=py310h23f4a51_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mccabe=0.6.1=py_1
  - multidict=6.0.2=py310h6acc77f_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nanotime=0.5.2=py_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - networkx=2.7.1=pyhd8ed1ab_0
  - numpy=1.22.3=py310h45f3432_0
  - openssl=1.1.1m=h7f8727e_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.1=py310hb5077e9_0
  - pango=1.48.10=h54213e6_2
  - parso=0.8.3=pyhd8ed1ab_0
  - pathlib2=2.3.7.post1=py310hff52083_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pcre2=10.37=h032f7d1_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - phonenumbers=8.12.44=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.0.1=py310h22f2fdc_0
  - pip=21.2.4=py310h06a4308_0
  - pixman=0.40.0=h36c2ea0_0
  - platformdirs=2.5.1=pyhd8ed1ab_0
  - pluggy=1.0.0=py310hff52083_2
  - ply=3.11=py_1
  - prompt-toolkit=3.0.27=pyha770c72_0
  - psutil=5.9.0=py310h6acc77f_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - py=1.11.0=pyh6c4a22f_0
  - py-xgboost=1.5.1=cpu_py310hd1aba9c_2
  - pyasn1=0.4.8=py_0
  - pycodestyle=2.8.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydot=1.4.2=py310hff52083_1
  - pyflakes=2.4.0=pyhd8ed1ab_0
  - pygit2=1.8.0=py310h6acc77f_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pygtrie=2.4.2=pyhd3deb0d_0
  - pylint=2.12.2=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd8ed1ab_1
  - pysocks=1.7.1=py310hff52083_4
  - pytest=7.0.1=py310hff52083_0
  - python=3.10.0=h12debd9_5
  - python-benedict=0.24.3=pyhd8ed1ab_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fsutil=0.6.0=pyhd8ed1ab_0
  - python-gssapi=1.7.3=py310h454a4aa_0
  - python-slugify=6.1.1=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2021.3=pyhd8ed1ab_0
  - pyyaml=6.0=py310h6acc77f_3
  - pyzmq=22.3.0=py310h675a958_1
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd8ed1ab_0
  - rich=11.2.0=pyhd8ed1ab_0
  - ruamel.yaml=0.17.21=py310h6acc77f_0
  - ruamel.yaml.clib=0.2.6=py310h6acc77f_0
  - s3fs=2022.2.0=pyhd8ed1ab_0
  - s3transfer=0.5.2=pyhd8ed1ab_0
  - scikit-learn=1.0.2=py310h1246948_0
  - scipy=1.8.0=py310hea5193d_1
  - scmrepo=0.0.7=pyhd8ed1ab_0
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - setuptools=58.0.4=py310h06a4308_0
  - shortuuid=1.0.8=py310hff52083_0
  - shtab=1.5.3=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - sqlite=3.37.2=hc218d9a_0
  - stack_data=0.2.0=pyhd8ed1ab_0
  - statsmodels=0.13.2=py310h96516ba_0
  - tabulate=0.8.9=pyhd8ed1ab_0
  - text-unidecode=1.3=py_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.11=h1ccaba5_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.1=py310h6acc77f_2
  - tqdm=4.63.0=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing-extensions=4.1.1=hd8ed1ab_0
  - typing_extensions=4.1.1=pyha770c72_0
  - tzdata=2021e=hda174b7_0
  - unicodedata2=14.0.0=py310h6acc77f_0
  - unidecode=1.3.3=pyhd8ed1ab_0
  - urllib3=1.26.8=pyhd8ed1ab_1
  - voluptuous=0.12.2=pyhd8ed1ab_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt=1.13.3=py310h6acc77f_1
  - xgboost=1.5.1=cpu_py310hd1aba9c_2
  - xlrd=2.0.1=pyhd8ed1ab_3
  - xmltodict=0.12.0=py_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.2=h470a237_5
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.7.2=py310h6acc77f_1
  - zc.lockfile=2.0=py_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.7.0=pyhd8ed1ab_1
  - zlib=1.2.11=h7f8727e_4
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - arrow==1.2.2
    - binaryornot==0.4.4
    - chardet==4.0.0
    - click==8.1.1
    - cookiecutter==1.7.3
    - jinja2==3.1.1
    - jinja2-time==0.2.0
    - markupsafe==2.1.1
    - poyo==0.5.0
prefix: /home/coder/local/bin/conda/envs/basesspcloud
